---
- name: Install media players
  snap:
    name:
      - vlc
      - spotify
  become: yes

- name: Install slack
  snap:
    name:
      - slack
    classic: yes
  become: yes

- name: Install apt media packages
  apt:
    pkg:
      - gimp
  become: yes
