---
- name: Install Main Packages
  apt:
    pkg:
      - build-essential
      - checkinstall
      - libreadline-gplv2-dev
      - libncursesw5-dev
      - libssl-dev
      - libsqlite3-dev
      - tk-dev
      - libgdbm-dev
      - libc6-dev
      - libbz2-dev
      - libffi-dev
      - zlib1g-dev
      - python
      - python3.8
      - git
      - docker
      - silversearcher-ag
      - libreoffice
      - curl
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common
      - awscli
      - openjdk-11-jdk
      - openjdk-11-jre
      - tree
      - net-tools
      - jupyter
  become: yes


- import_tasks: security.yml
- import_tasks: external.yml
# - import_tasks: boostnote.yml
- import_tasks: terminator.yml
- import_tasks: pip.yml
- import_tasks: vimrc.yml
- import_tasks: fzf.yml
- import_tasks: git.yml
