---
- name: Install Python
  apt:
    pkg:
      - python-pip
      - python3-venv
      - python3-pip

- name: Install setuptools
  shell: pip install setuptools

- name: Install some pip packages
  pip:
    name:
      - ipython

- name: Install some pip3 packages
  pip:
    executable: pip3
    name:
      - virtualenvwrapper
      - ipython
