---
- name: Install Python3
  apt:
    pkg:
      - python3-setuptools
      - python3-venv
      - python3-pip
      - python3.8
  become: yes

- name: Install setuptools
  shell: pip install setuptools
  become: yes

- name: Install some pip3 packages
  pip:
    executable: pip3
    name:
      - virtualenvwrapper
      - ipython
      - docker-compose
  become: no

- name: Install some pip packages
  pip:
    executable: pip
    name:
      - docker-compose
  become: no
