---
- name: Install Python
  apt:
    pkg:
      - python-pip
      - python3-venv
      - python3-pip
  become: yes

- name: Install setuptools
  shell: pip install setuptools
  become: yes

- name: Install some pip2 packages
  pip:
    name:
      - ipython

- name: Install some pip3 packages
  pip:
    executable: pip3
    name:
      - virtualenvwrapper
      - ipython

- name: Install some pip packages
  pip:
    executable: pip
    name:
      - docker-compose
  become: yes
